name: ev2-cloud-ecommerce

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: ev2-postgres-db
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ev2-backend
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres-db:5432/ecommerce
      JWT_SECRET_KEY: dev-secret-key-with-enough-length

      # FIX IMPORTANTE
      CORS_ORIGINS: http://localhost:4200

      AUTO_CREATE_TABLES: "true"
      AUTO_SEED_PRODUCTS: "true"
    ports:
      - "8000:8000"
    networks:
      - microservices-network
    depends_on:
      - postgres-db
    restart: unless-stopped

  app-pagos:
    build:
      context: ./microservicios/app-pagos
    container_name: ev2-app-pagos
    environment:
      MP_ACCESS_TOKEN: ${MP_ACCESS_TOKEN:-}
      MP_PUBLIC_KEY: ${MP_PUBLIC_KEY:-}

      MP_SUCCESS_URL: http://localhost:4200
      MP_FAILURE_URL: http://localhost:4200
      MP_PENDING_URL: http://localhost:4200
    ports:
      - "8002:8002"
    networks:
      - microservices-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: ev2-frontend
    ports:
      - "80:80"
    networks:
      - microservices-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge

volumes:
  postgres_data: